modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/Iunius118/ChiliBulletWeapons/issues"
license = "MIT license"

[[mods]]
modId = "chilibulletweapons"
version = "${version}"
displayName = "Chili Bullet Weapons"
displayURL= "https://github.com/Iunius118/ChiliBulletWeapons"
authors = "Iunius118"
description = '''
Adds chili pepper, weapons, and foods.
'''
logoFile = "assets/chilibulletweapons/icon.png"

[[dependencies.chilibulletweapons]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chilibulletweapons]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chilibulletweapons]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.1,)"
ordering = "AFTER"
side = "BOTH"
